import type { Metadata } from 'next'
import { Gowun_Batang, Inter } from 'next/font/google'
import './globals.css'

const gowunBatang = Gowun_Batang({ weight: ['400', '700'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={gowunBatang.className}>{children}</body>
    </html>
  )
}
